# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/litchi/httpserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/litchi/httpserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/litchi/httpserver/CMakeFiles /root/litchi/httpserver//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/litchi/httpserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named httpServer

# Build rule for target.
httpServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 httpServer
.PHONY : httpServer

# fast build rule for target.
httpServer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/build
.PHONY : httpServer/fast

inc/asyncLogging.o: inc/asyncLogging.cpp.o
.PHONY : inc/asyncLogging.o

# target to build an object file
inc/asyncLogging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/asyncLogging.cpp.o
.PHONY : inc/asyncLogging.cpp.o

inc/asyncLogging.i: inc/asyncLogging.cpp.i
.PHONY : inc/asyncLogging.i

# target to preprocess a source file
inc/asyncLogging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/asyncLogging.cpp.i
.PHONY : inc/asyncLogging.cpp.i

inc/asyncLogging.s: inc/asyncLogging.cpp.s
.PHONY : inc/asyncLogging.s

# target to generate assembly for a file
inc/asyncLogging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/asyncLogging.cpp.s
.PHONY : inc/asyncLogging.cpp.s

inc/buffer.o: inc/buffer.cpp.o
.PHONY : inc/buffer.o

# target to build an object file
inc/buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/buffer.cpp.o
.PHONY : inc/buffer.cpp.o

inc/buffer.i: inc/buffer.cpp.i
.PHONY : inc/buffer.i

# target to preprocess a source file
inc/buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/buffer.cpp.i
.PHONY : inc/buffer.cpp.i

inc/buffer.s: inc/buffer.cpp.s
.PHONY : inc/buffer.s

# target to generate assembly for a file
inc/buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/buffer.cpp.s
.PHONY : inc/buffer.cpp.s

inc/channel.o: inc/channel.cpp.o
.PHONY : inc/channel.o

# target to build an object file
inc/channel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/channel.cpp.o
.PHONY : inc/channel.cpp.o

inc/channel.i: inc/channel.cpp.i
.PHONY : inc/channel.i

# target to preprocess a source file
inc/channel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/channel.cpp.i
.PHONY : inc/channel.cpp.i

inc/channel.s: inc/channel.cpp.s
.PHONY : inc/channel.s

# target to generate assembly for a file
inc/channel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/channel.cpp.s
.PHONY : inc/channel.cpp.s

inc/connector.o: inc/connector.cpp.o
.PHONY : inc/connector.o

# target to build an object file
inc/connector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/connector.cpp.o
.PHONY : inc/connector.cpp.o

inc/connector.i: inc/connector.cpp.i
.PHONY : inc/connector.i

# target to preprocess a source file
inc/connector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/connector.cpp.i
.PHONY : inc/connector.cpp.i

inc/connector.s: inc/connector.cpp.s
.PHONY : inc/connector.s

# target to generate assembly for a file
inc/connector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/connector.cpp.s
.PHONY : inc/connector.cpp.s

inc/epoller.o: inc/epoller.cpp.o
.PHONY : inc/epoller.o

# target to build an object file
inc/epoller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/epoller.cpp.o
.PHONY : inc/epoller.cpp.o

inc/epoller.i: inc/epoller.cpp.i
.PHONY : inc/epoller.i

# target to preprocess a source file
inc/epoller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/epoller.cpp.i
.PHONY : inc/epoller.cpp.i

inc/epoller.s: inc/epoller.cpp.s
.PHONY : inc/epoller.s

# target to generate assembly for a file
inc/epoller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/epoller.cpp.s
.PHONY : inc/epoller.cpp.s

inc/eventLoop.o: inc/eventLoop.cpp.o
.PHONY : inc/eventLoop.o

# target to build an object file
inc/eventLoop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/eventLoop.cpp.o
.PHONY : inc/eventLoop.cpp.o

inc/eventLoop.i: inc/eventLoop.cpp.i
.PHONY : inc/eventLoop.i

# target to preprocess a source file
inc/eventLoop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/eventLoop.cpp.i
.PHONY : inc/eventLoop.cpp.i

inc/eventLoop.s: inc/eventLoop.cpp.s
.PHONY : inc/eventLoop.s

# target to generate assembly for a file
inc/eventLoop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/eventLoop.cpp.s
.PHONY : inc/eventLoop.cpp.s

inc/eventLoopThread.o: inc/eventLoopThread.cpp.o
.PHONY : inc/eventLoopThread.o

# target to build an object file
inc/eventLoopThread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/eventLoopThread.cpp.o
.PHONY : inc/eventLoopThread.cpp.o

inc/eventLoopThread.i: inc/eventLoopThread.cpp.i
.PHONY : inc/eventLoopThread.i

# target to preprocess a source file
inc/eventLoopThread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/eventLoopThread.cpp.i
.PHONY : inc/eventLoopThread.cpp.i

inc/eventLoopThread.s: inc/eventLoopThread.cpp.s
.PHONY : inc/eventLoopThread.s

# target to generate assembly for a file
inc/eventLoopThread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/eventLoopThread.cpp.s
.PHONY : inc/eventLoopThread.cpp.s

inc/eventLoopThreadPool.o: inc/eventLoopThreadPool.cpp.o
.PHONY : inc/eventLoopThreadPool.o

# target to build an object file
inc/eventLoopThreadPool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/eventLoopThreadPool.cpp.o
.PHONY : inc/eventLoopThreadPool.cpp.o

inc/eventLoopThreadPool.i: inc/eventLoopThreadPool.cpp.i
.PHONY : inc/eventLoopThreadPool.i

# target to preprocess a source file
inc/eventLoopThreadPool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/eventLoopThreadPool.cpp.i
.PHONY : inc/eventLoopThreadPool.cpp.i

inc/eventLoopThreadPool.s: inc/eventLoopThreadPool.cpp.s
.PHONY : inc/eventLoopThreadPool.s

# target to generate assembly for a file
inc/eventLoopThreadPool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/eventLoopThreadPool.cpp.s
.PHONY : inc/eventLoopThreadPool.cpp.s

inc/httpContext.o: inc/httpContext.cpp.o
.PHONY : inc/httpContext.o

# target to build an object file
inc/httpContext.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/httpContext.cpp.o
.PHONY : inc/httpContext.cpp.o

inc/httpContext.i: inc/httpContext.cpp.i
.PHONY : inc/httpContext.i

# target to preprocess a source file
inc/httpContext.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/httpContext.cpp.i
.PHONY : inc/httpContext.cpp.i

inc/httpContext.s: inc/httpContext.cpp.s
.PHONY : inc/httpContext.s

# target to generate assembly for a file
inc/httpContext.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/httpContext.cpp.s
.PHONY : inc/httpContext.cpp.s

inc/httpResponse.o: inc/httpResponse.cpp.o
.PHONY : inc/httpResponse.o

# target to build an object file
inc/httpResponse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/httpResponse.cpp.o
.PHONY : inc/httpResponse.cpp.o

inc/httpResponse.i: inc/httpResponse.cpp.i
.PHONY : inc/httpResponse.i

# target to preprocess a source file
inc/httpResponse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/httpResponse.cpp.i
.PHONY : inc/httpResponse.cpp.i

inc/httpResponse.s: inc/httpResponse.cpp.s
.PHONY : inc/httpResponse.s

# target to generate assembly for a file
inc/httpResponse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/httpResponse.cpp.s
.PHONY : inc/httpResponse.cpp.s

inc/httpServer.o: inc/httpServer.cpp.o
.PHONY : inc/httpServer.o

# target to build an object file
inc/httpServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/httpServer.cpp.o
.PHONY : inc/httpServer.cpp.o

inc/httpServer.i: inc/httpServer.cpp.i
.PHONY : inc/httpServer.i

# target to preprocess a source file
inc/httpServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/httpServer.cpp.i
.PHONY : inc/httpServer.cpp.i

inc/httpServer.s: inc/httpServer.cpp.s
.PHONY : inc/httpServer.s

# target to generate assembly for a file
inc/httpServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/httpServer.cpp.s
.PHONY : inc/httpServer.cpp.s

inc/logFile.o: inc/logFile.cpp.o
.PHONY : inc/logFile.o

# target to build an object file
inc/logFile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/logFile.cpp.o
.PHONY : inc/logFile.cpp.o

inc/logFile.i: inc/logFile.cpp.i
.PHONY : inc/logFile.i

# target to preprocess a source file
inc/logFile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/logFile.cpp.i
.PHONY : inc/logFile.cpp.i

inc/logFile.s: inc/logFile.cpp.s
.PHONY : inc/logFile.s

# target to generate assembly for a file
inc/logFile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/logFile.cpp.s
.PHONY : inc/logFile.cpp.s

inc/logStream.o: inc/logStream.cpp.o
.PHONY : inc/logStream.o

# target to build an object file
inc/logStream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/logStream.cpp.o
.PHONY : inc/logStream.cpp.o

inc/logStream.i: inc/logStream.cpp.i
.PHONY : inc/logStream.i

# target to preprocess a source file
inc/logStream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/logStream.cpp.i
.PHONY : inc/logStream.cpp.i

inc/logStream.s: inc/logStream.cpp.s
.PHONY : inc/logStream.s

# target to generate assembly for a file
inc/logStream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/logStream.cpp.s
.PHONY : inc/logStream.cpp.s

inc/logging.o: inc/logging.cpp.o
.PHONY : inc/logging.o

# target to build an object file
inc/logging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/logging.cpp.o
.PHONY : inc/logging.cpp.o

inc/logging.i: inc/logging.cpp.i
.PHONY : inc/logging.i

# target to preprocess a source file
inc/logging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/logging.cpp.i
.PHONY : inc/logging.cpp.i

inc/logging.s: inc/logging.cpp.s
.PHONY : inc/logging.s

# target to generate assembly for a file
inc/logging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/logging.cpp.s
.PHONY : inc/logging.cpp.s

inc/mAcceptor.o: inc/mAcceptor.cpp.o
.PHONY : inc/mAcceptor.o

# target to build an object file
inc/mAcceptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/mAcceptor.cpp.o
.PHONY : inc/mAcceptor.cpp.o

inc/mAcceptor.i: inc/mAcceptor.cpp.i
.PHONY : inc/mAcceptor.i

# target to preprocess a source file
inc/mAcceptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/mAcceptor.cpp.i
.PHONY : inc/mAcceptor.cpp.i

inc/mAcceptor.s: inc/mAcceptor.cpp.s
.PHONY : inc/mAcceptor.s

# target to generate assembly for a file
inc/mAcceptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/mAcceptor.cpp.s
.PHONY : inc/mAcceptor.cpp.s

inc/mInetAddress.o: inc/mInetAddress.cpp.o
.PHONY : inc/mInetAddress.o

# target to build an object file
inc/mInetAddress.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/mInetAddress.cpp.o
.PHONY : inc/mInetAddress.cpp.o

inc/mInetAddress.i: inc/mInetAddress.cpp.i
.PHONY : inc/mInetAddress.i

# target to preprocess a source file
inc/mInetAddress.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/mInetAddress.cpp.i
.PHONY : inc/mInetAddress.cpp.i

inc/mInetAddress.s: inc/mInetAddress.cpp.s
.PHONY : inc/mInetAddress.s

# target to generate assembly for a file
inc/mInetAddress.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/mInetAddress.cpp.s
.PHONY : inc/mInetAddress.cpp.s

inc/mSocket.o: inc/mSocket.cpp.o
.PHONY : inc/mSocket.o

# target to build an object file
inc/mSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/mSocket.cpp.o
.PHONY : inc/mSocket.cpp.o

inc/mSocket.i: inc/mSocket.cpp.i
.PHONY : inc/mSocket.i

# target to preprocess a source file
inc/mSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/mSocket.cpp.i
.PHONY : inc/mSocket.cpp.i

inc/mSocket.s: inc/mSocket.cpp.s
.PHONY : inc/mSocket.s

# target to generate assembly for a file
inc/mSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/mSocket.cpp.s
.PHONY : inc/mSocket.cpp.s

inc/memoryPool.o: inc/memoryPool.cpp.o
.PHONY : inc/memoryPool.o

# target to build an object file
inc/memoryPool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/memoryPool.cpp.o
.PHONY : inc/memoryPool.cpp.o

inc/memoryPool.i: inc/memoryPool.cpp.i
.PHONY : inc/memoryPool.i

# target to preprocess a source file
inc/memoryPool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/memoryPool.cpp.i
.PHONY : inc/memoryPool.cpp.i

inc/memoryPool.s: inc/memoryPool.cpp.s
.PHONY : inc/memoryPool.s

# target to generate assembly for a file
inc/memoryPool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/memoryPool.cpp.s
.PHONY : inc/memoryPool.cpp.s

inc/tcpClient.o: inc/tcpClient.cpp.o
.PHONY : inc/tcpClient.o

# target to build an object file
inc/tcpClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/tcpClient.cpp.o
.PHONY : inc/tcpClient.cpp.o

inc/tcpClient.i: inc/tcpClient.cpp.i
.PHONY : inc/tcpClient.i

# target to preprocess a source file
inc/tcpClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/tcpClient.cpp.i
.PHONY : inc/tcpClient.cpp.i

inc/tcpClient.s: inc/tcpClient.cpp.s
.PHONY : inc/tcpClient.s

# target to generate assembly for a file
inc/tcpClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/tcpClient.cpp.s
.PHONY : inc/tcpClient.cpp.s

inc/tcpConnection.o: inc/tcpConnection.cpp.o
.PHONY : inc/tcpConnection.o

# target to build an object file
inc/tcpConnection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/tcpConnection.cpp.o
.PHONY : inc/tcpConnection.cpp.o

inc/tcpConnection.i: inc/tcpConnection.cpp.i
.PHONY : inc/tcpConnection.i

# target to preprocess a source file
inc/tcpConnection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/tcpConnection.cpp.i
.PHONY : inc/tcpConnection.cpp.i

inc/tcpConnection.s: inc/tcpConnection.cpp.s
.PHONY : inc/tcpConnection.s

# target to generate assembly for a file
inc/tcpConnection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/tcpConnection.cpp.s
.PHONY : inc/tcpConnection.cpp.s

inc/tcpServer.o: inc/tcpServer.cpp.o
.PHONY : inc/tcpServer.o

# target to build an object file
inc/tcpServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/tcpServer.cpp.o
.PHONY : inc/tcpServer.cpp.o

inc/tcpServer.i: inc/tcpServer.cpp.i
.PHONY : inc/tcpServer.i

# target to preprocess a source file
inc/tcpServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/tcpServer.cpp.i
.PHONY : inc/tcpServer.cpp.i

inc/tcpServer.s: inc/tcpServer.cpp.s
.PHONY : inc/tcpServer.s

# target to generate assembly for a file
inc/tcpServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/tcpServer.cpp.s
.PHONY : inc/tcpServer.cpp.s

inc/thread.o: inc/thread.cpp.o
.PHONY : inc/thread.o

# target to build an object file
inc/thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/thread.cpp.o
.PHONY : inc/thread.cpp.o

inc/thread.i: inc/thread.cpp.i
.PHONY : inc/thread.i

# target to preprocess a source file
inc/thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/thread.cpp.i
.PHONY : inc/thread.cpp.i

inc/thread.s: inc/thread.cpp.s
.PHONY : inc/thread.s

# target to generate assembly for a file
inc/thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/thread.cpp.s
.PHONY : inc/thread.cpp.s

inc/timer.o: inc/timer.cpp.o
.PHONY : inc/timer.o

# target to build an object file
inc/timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/timer.cpp.o
.PHONY : inc/timer.cpp.o

inc/timer.i: inc/timer.cpp.i
.PHONY : inc/timer.i

# target to preprocess a source file
inc/timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/timer.cpp.i
.PHONY : inc/timer.cpp.i

inc/timer.s: inc/timer.cpp.s
.PHONY : inc/timer.s

# target to generate assembly for a file
inc/timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/timer.cpp.s
.PHONY : inc/timer.cpp.s

inc/timerQueue.o: inc/timerQueue.cpp.o
.PHONY : inc/timerQueue.o

# target to build an object file
inc/timerQueue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/timerQueue.cpp.o
.PHONY : inc/timerQueue.cpp.o

inc/timerQueue.i: inc/timerQueue.cpp.i
.PHONY : inc/timerQueue.i

# target to preprocess a source file
inc/timerQueue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/timerQueue.cpp.i
.PHONY : inc/timerQueue.cpp.i

inc/timerQueue.s: inc/timerQueue.cpp.s
.PHONY : inc/timerQueue.s

# target to generate assembly for a file
inc/timerQueue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/timerQueue.cpp.s
.PHONY : inc/timerQueue.cpp.s

inc/timestamp.o: inc/timestamp.cpp.o
.PHONY : inc/timestamp.o

# target to build an object file
inc/timestamp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/timestamp.cpp.o
.PHONY : inc/timestamp.cpp.o

inc/timestamp.i: inc/timestamp.cpp.i
.PHONY : inc/timestamp.i

# target to preprocess a source file
inc/timestamp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/timestamp.cpp.i
.PHONY : inc/timestamp.cpp.i

inc/timestamp.s: inc/timestamp.cpp.s
.PHONY : inc/timestamp.s

# target to generate assembly for a file
inc/timestamp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/inc/timestamp.cpp.s
.PHONY : inc/timestamp.cpp.s

serverStart.o: serverStart.cpp.o
.PHONY : serverStart.o

# target to build an object file
serverStart.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/serverStart.cpp.o
.PHONY : serverStart.cpp.o

serverStart.i: serverStart.cpp.i
.PHONY : serverStart.i

# target to preprocess a source file
serverStart.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/serverStart.cpp.i
.PHONY : serverStart.cpp.i

serverStart.s: serverStart.cpp.s
.PHONY : serverStart.s

# target to generate assembly for a file
serverStart.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/serverStart.cpp.s
.PHONY : serverStart.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... httpServer"
	@echo "... inc/asyncLogging.o"
	@echo "... inc/asyncLogging.i"
	@echo "... inc/asyncLogging.s"
	@echo "... inc/buffer.o"
	@echo "... inc/buffer.i"
	@echo "... inc/buffer.s"
	@echo "... inc/channel.o"
	@echo "... inc/channel.i"
	@echo "... inc/channel.s"
	@echo "... inc/connector.o"
	@echo "... inc/connector.i"
	@echo "... inc/connector.s"
	@echo "... inc/epoller.o"
	@echo "... inc/epoller.i"
	@echo "... inc/epoller.s"
	@echo "... inc/eventLoop.o"
	@echo "... inc/eventLoop.i"
	@echo "... inc/eventLoop.s"
	@echo "... inc/eventLoopThread.o"
	@echo "... inc/eventLoopThread.i"
	@echo "... inc/eventLoopThread.s"
	@echo "... inc/eventLoopThreadPool.o"
	@echo "... inc/eventLoopThreadPool.i"
	@echo "... inc/eventLoopThreadPool.s"
	@echo "... inc/httpContext.o"
	@echo "... inc/httpContext.i"
	@echo "... inc/httpContext.s"
	@echo "... inc/httpResponse.o"
	@echo "... inc/httpResponse.i"
	@echo "... inc/httpResponse.s"
	@echo "... inc/httpServer.o"
	@echo "... inc/httpServer.i"
	@echo "... inc/httpServer.s"
	@echo "... inc/logFile.o"
	@echo "... inc/logFile.i"
	@echo "... inc/logFile.s"
	@echo "... inc/logStream.o"
	@echo "... inc/logStream.i"
	@echo "... inc/logStream.s"
	@echo "... inc/logging.o"
	@echo "... inc/logging.i"
	@echo "... inc/logging.s"
	@echo "... inc/mAcceptor.o"
	@echo "... inc/mAcceptor.i"
	@echo "... inc/mAcceptor.s"
	@echo "... inc/mInetAddress.o"
	@echo "... inc/mInetAddress.i"
	@echo "... inc/mInetAddress.s"
	@echo "... inc/mSocket.o"
	@echo "... inc/mSocket.i"
	@echo "... inc/mSocket.s"
	@echo "... inc/memoryPool.o"
	@echo "... inc/memoryPool.i"
	@echo "... inc/memoryPool.s"
	@echo "... inc/tcpClient.o"
	@echo "... inc/tcpClient.i"
	@echo "... inc/tcpClient.s"
	@echo "... inc/tcpConnection.o"
	@echo "... inc/tcpConnection.i"
	@echo "... inc/tcpConnection.s"
	@echo "... inc/tcpServer.o"
	@echo "... inc/tcpServer.i"
	@echo "... inc/tcpServer.s"
	@echo "... inc/thread.o"
	@echo "... inc/thread.i"
	@echo "... inc/thread.s"
	@echo "... inc/timer.o"
	@echo "... inc/timer.i"
	@echo "... inc/timer.s"
	@echo "... inc/timerQueue.o"
	@echo "... inc/timerQueue.i"
	@echo "... inc/timerQueue.s"
	@echo "... inc/timestamp.o"
	@echo "... inc/timestamp.i"
	@echo "... inc/timestamp.s"
	@echo "... serverStart.o"
	@echo "... serverStart.i"
	@echo "... serverStart.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

